name: Changelog and Discord Notification

on:
  push:
    branches:
      - main

jobs:
  update_and_notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permissions to push back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need full history for changelog generation

      # Store the initial state of CHANGELOG.md
      - name: Store initial CHANGELOG.md
        id: initial_changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md > initial_CHANGELOG.md
          else
            touch initial_CHANGELOG.md
          fi

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"
          git-message: "chore: update changelog"
          git-user-name: "github-actions[bot]"
          git-user-email: "github-actions[bot]@users.noreply.github.com"
          version-file: "version/version.json"
          version-path: "version"
          skip-version-file: 'true' # Skip version file update
          skip-tag: 'true' # Skip tag creation if it already exists

      - name: Send Discord Notification
        # Only send notification if the changelog action actually made changes
        if: steps.changelog.outputs.changelog != ''
        run: |
          set -x # Enable debugging
          WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          # Construct the JSON payload using jq
          JSON_PAYLOAD=$(jq -n \
            --arg content "📜 **Changelog Updated**\n${{ steps.changelog.outputs.changelog }}" \
            '{content: $content}'\
          )
          curl -v -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$WEBHOOK_URL"

      - name: Trigger Release Workflow
        # Only trigger if the changelog action actually made changes and a new version was determined
        if: steps.changelog.outputs.new_version != ''
        run: |
          set -x # Enable debugging
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches \
          -d '{"ref":"main","inputs":{"version":"${{ steps.changelog.outputs.new_version }}"}}'
